/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package common;

import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author martin
 */
public class SwingGUI01 extends javax.swing.JFrame {
    
    /**
     * Creates new form SwingGUI01
     */
    public SwingGUI01() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addAgentDialog = new javax.swing.JDialog();
        label1 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        assignAgentToMissionButton = new javax.swing.JButton();
        findAgentsOnMissionButton = new javax.swing.JButton();
        findAvailableAgentsButton = new javax.swing.JButton();
        findAvailableAgentsForMissionButton = new javax.swing.JButton();
        findMissionWithAgentButton = new javax.swing.JButton();
        withdrawAgentFromMissionButton = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        agentsTable = new javax.swing.JTable();
        addAgentButton = new javax.swing.JButton();
        editAgentButton = new javax.swing.JButton();
        deleteAgentButton = new javax.swing.JButton();
        findAgentButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        missionsTable = new javax.swing.JTable();
        addMissionButton = new javax.swing.JButton();
        editMissionButton = new javax.swing.JButton();
        deleteMissionButton = new javax.swing.JButton();
        findMissionButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        connectDBMenuItem = new javax.swing.JMenuItem();
        disconnectDBMenuItem = new javax.swing.JMenuItem();
        reloadDBMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        label1.setText("label1");

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout addAgentDialogLayout = new javax.swing.GroupLayout(addAgentDialog.getContentPane());
        addAgentDialog.getContentPane().setLayout(addAgentDialogLayout);
        addAgentDialogLayout.setHorizontalGroup(
            addAgentDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addAgentDialogLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addAgentDialogLayout.createSequentialGroup()
                .addContainerGap(234, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(126, 126, 126))
        );
        addAgentDialogLayout.setVerticalGroup(
            addAgentDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addAgentDialogLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(jLabel1)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusTraversalPolicyProvider(true);
        setMinimumSize(new java.awt.Dimension(300, 200));
        setName("Main"); // NOI18N
        setPreferredSize(new java.awt.Dimension(880, 550));
        setResizable(false);

        jLayeredPane1.setPreferredSize(new java.awt.Dimension(800, 528));

        assignAgentToMissionButton.setText("assign agent to mission");

        findAgentsOnMissionButton.setText("find agents on mission");

        findAvailableAgentsButton.setText("find available agents");

        findAvailableAgentsForMissionButton.setText("find available agents for mission");

        findMissionWithAgentButton.setText("find mission with agent");
        findMissionWithAgentButton.setToolTipText("");

        withdrawAgentFromMissionButton.setText("withdraw agent from mission");

        jPanel1.setPreferredSize(new java.awt.Dimension(932, 530));

        agentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "name", "born", "level", "note"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(agentsTable);
        if (agentsTable.getColumnModel().getColumnCount() > 0) {
            agentsTable.getColumnModel().getColumn(0).setResizable(false);
            agentsTable.getColumnModel().getColumn(1).setResizable(false);
            agentsTable.getColumnModel().getColumn(2).setResizable(false);
            agentsTable.getColumnModel().getColumn(3).setResizable(false);
            agentsTable.getColumnModel().getColumn(4).setResizable(false);
        }

        addAgentButton.setText("add agent");
        addAgentButton.setName("addAgentButton"); // NOI18N
        addAgentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAgentButtonActionPerformed(evt);
            }
        });

        editAgentButton.setText("edit agent");
        editAgentButton.setName("editAgentButton"); // NOI18N

        deleteAgentButton.setText("delete agent");
        deleteAgentButton.setName("deleteAgentButton"); // NOI18N

        findAgentButton.setText("find agent");
        findAgentButton.setName("findAgentButton"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 875, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addAgentButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editAgentButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteAgentButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(findAgentButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addAgentButton)
                    .addComponent(editAgentButton)
                    .addComponent(deleteAgentButton)
                    .addComponent(findAgentButton))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Agents table", jPanel1);

        missionsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "beginDate", "endDate", "difficulty", "capacity", "note"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(missionsTable);
        if (missionsTable.getColumnModel().getColumnCount() > 0) {
            missionsTable.getColumnModel().getColumn(0).setResizable(false);
            missionsTable.getColumnModel().getColumn(1).setResizable(false);
            missionsTable.getColumnModel().getColumn(2).setResizable(false);
            missionsTable.getColumnModel().getColumn(3).setResizable(false);
            missionsTable.getColumnModel().getColumn(4).setResizable(false);
            missionsTable.getColumnModel().getColumn(5).setResizable(false);
        }

        addMissionButton.setText("add mission");
        addMissionButton.setName("addMissionButton"); // NOI18N

        editMissionButton.setText("edit mission");
        editMissionButton.setName("editMissionButton"); // NOI18N

        deleteMissionButton.setText("delete mission");
        deleteMissionButton.setName("deleteMissionButton"); // NOI18N

        findMissionButton.setText("find mission");
        findMissionButton.setName("findMissionButton"); // NOI18N
        findMissionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findMissionButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addMissionButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editMissionButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteMissionButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(findMissionButton)
                .addContainerGap(400, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(findMissionButton)
                    .addComponent(deleteMissionButton)
                    .addComponent(editMissionButton)
                    .addComponent(addMissionButton))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Missions table", jPanel2);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(assignAgentToMissionButton)
                .addGap(91, 91, 91)
                .addComponent(findAgentsOnMissionButton)
                .addGap(82, 82, 82)
                .addComponent(findAvailableAgentsButton)
                .addContainerGap(195, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(findAvailableAgentsForMissionButton)
                .addGap(76, 76, 76)
                .addComponent(findMissionWithAgentButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(withdrawAgentFromMissionButton)
                .addGap(27, 27, 27))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assignAgentToMissionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findAgentsOnMissionButton)
                    .addComponent(findAvailableAgentsButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(withdrawAgentFromMissionButton)
                    .addComponent(findMissionWithAgentButton)
                    .addComponent(findAvailableAgentsForMissionButton))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jLayeredPane1.setLayer(assignAgentToMissionButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(findAgentsOnMissionButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(findAvailableAgentsButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(findAvailableAgentsForMissionButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(findMissionWithAgentButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(withdrawAgentFromMissionButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jTabbedPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenuBar1.setName("AgentsTable"); // NOI18N

        jMenu1.setText("File");

        connectDBMenuItem.setText("Connect to DB");
        jMenu1.add(connectDBMenuItem);

        disconnectDBMenuItem.setText("Disconnect the DB");
        disconnectDBMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disconnectDBMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(disconnectDBMenuItem);

        reloadDBMenuItem.setText("Reload the DB");
        jMenu1.add(reloadDBMenuItem);

        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(exitMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void findMissionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findMissionButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_findMissionButtonActionPerformed

    private void addAgentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAgentButtonActionPerformed
        addAgentDialog.setVisible(true);
    }//GEN-LAST:event_addAgentButtonActionPerformed

    private void disconnectDBMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disconnectDBMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_disconnectDBMenuItemActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SwingGUI01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SwingGUI01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SwingGUI01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SwingGUI01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SwingGUI01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAgentButton;
    private javax.swing.JDialog addAgentDialog;
    private javax.swing.JButton addMissionButton;
    private javax.swing.JTable agentsTable;
    private javax.swing.JButton assignAgentToMissionButton;
    private javax.swing.JMenuItem connectDBMenuItem;
    private javax.swing.JButton deleteAgentButton;
    private javax.swing.JButton deleteMissionButton;
    private javax.swing.JMenuItem disconnectDBMenuItem;
    private javax.swing.JButton editAgentButton;
    private javax.swing.JButton editMissionButton;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JButton findAgentButton;
    private javax.swing.JButton findAgentsOnMissionButton;
    private javax.swing.JButton findAvailableAgentsButton;
    private javax.swing.JButton findAvailableAgentsForMissionButton;
    private javax.swing.JButton findMissionButton;
    private javax.swing.JButton findMissionWithAgentButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private java.awt.Label label1;
    private javax.swing.JTable missionsTable;
    private javax.swing.JMenuItem reloadDBMenuItem;
    private javax.swing.JButton withdrawAgentFromMissionButton;
    // End of variables declaration//GEN-END:variables
}
